### PR TITLE
Authentication test

### PR DESCRIPTION
**Pull request by henrywang1**

### CODE REVIEW

**Comment by henrywang1** [comment]
This is still a draft, you don't need to review.

**Comment by henrywang1** [comment]
### Changes:
1. Use SendGrid to send forgot password email
2. Use email_spec to test
3. Move all `%Howdy, #{@current_user.firstname}!` under the logo image to `zlp-scheduler/app/views/layouts/application.html.haml` for consistency
    - application.html is the default for rendering any page
    - we need to clean browser cache to see the difference

### Note:
1. `email_steps.rb ` is generated from email_spec, and I only changed line 33
2. We need to set sender's email before delivering the product to the customer
    - modify the "from" in `application_mailer.rb`
    - [create a sender](https://app.sendgrid.com/settings/sender_auth/senders/new)  on SendGrid for the "from" email
3. We also need to [setup sendgrid on Heroku](https://devcenter.heroku.com/articles/sendgrid) before delivering the product to the customer

**Comment by BWitemeyer** [comment]
This looks great! On the moving of the `Howdy, User!` to the application view, would it be possible to remove that code from this pull request? We can discuss at scrum whether we want to consolidate that code, but I think it would be better to have it in its own PR if we decide to do that.

**Comment by henrywang1** [comment]
> This looks great! On the moving of the `Howdy, User!` to the application view, would it be possible to remove that code from this pull request? We can discuss at scrum whether we want to consolidate that code, but I think it would be better to have it in its own PR if we decide to do that.

Thanks, I will move them to another PR.

**Pull request merged**
