### PR TITLE
View student schedule testing

### PR DESCRIPTION
**Pull request by John-STJB**
Modified factories
Add View student schedule testing
(features and step_definition)

### CODE REVIEW

**Comment by John-STJB** [comment]
Please Use Squash before merge, because accidently using wrong username.

**Review by henrywang1 — APPROVED** [review]
Some commented out code should be removed in the future, but overall the newly added tests are ok .
Also, thanks for removed the unused cohort id for my previously added tests.

**Comment by BWitemeyer** [comment]
Looks good to me, although the file naming isn't consistent with the other files in the testing features. Not something that has to change, but it might be a good idea to be consistent with naming.

**Comment by adauzat90** [comment]
Looks good to me nothing really to add that hasn't already been said

**Review by adauzat90 — APPROVED** [review]

**Pull request merged**
