### PR TITLE
Add Time preference cost

### PR DESCRIPTION
**Pull request by Sanghyeon16**
Add Time Preferences - Algorithm

This is the time preference algorithm that generates time costs.
I used two sigmoid functions so that both of the edges of timeslots have higher costs and the main (8am-5pm) timeslots have almost 0 costs.

### CODE REVIEW

**Review by BWitemeyer — CHANGES_REQUESTED** [review]
This looks great, but we talked in the customer meeting about making 8:00 a hard preference only. Would it be possible to modify this code to only calculate the soft preferences for times after 5:00?

**Review by MinhDang98 — APPROVED** [review]

**Comment by Sanghyeon16** [comment]
> This looks great, but we talked in the customer meeting about making 8:00 a hard preference only. Would it be possible to modify this code to only calculate the soft preferences for times after 5:00?

Sure!

**Comment by Sanghyeon16** [comment]
> This looks great, but we talked in the customer meeting about making 8:00 a hard preference only. Would it be possible to modify this code to only calculate the soft preferences for times after 5:00?

Sure! I updated the change!

**Review by BWitemeyer — APPROVED** [review]
Looks great!

**Pull request merged**
